config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "/signup", to: "users#new"
  resources :users do
    get "/followers", to: "users#followers"
    get "/following", to: "users#followees"
    get "credits"
    member do
      get :confirm_email
      post "follow"
      post "unfollow"
    end
  end

  resources :credit_packs, only: [:index]
  resource :transactions, only: [:create]
  resources :orders, only: [:create], param: :code do
    get "checkout", on: :member
    get "success", on: :member
    get "failure", on: :member
  end
  resources :passwords
  resources :sessions, only: [:new, :create, :destroy]
  resources :reports
  resources :questions, param: :permalink do
    resources :answers do
      resources :comments
    end
    resources :comments
    collection do
      match "search" => "questions#search", via: [:get, :post], as: :search
    end
  end

  namespace :api do
    get 'feed', to: 'users#feed', format: true, constraints: { format: :json }
    resources :topics, only: [:index, :show], param: :topic do
      get "/:x", to: "topics#show", on: :member
    end
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
end

app/models/user.rb
class User < ApplicationRecord
  include ::TokenHandler
  enum role: {
    "user" => 0,
    "admin" => 1,
  }

  before_create -> { generate_token(:email_confirm_token) }
  after_create_commit :send_confirmation_email
  before_save :downcase_email
  before_update :add_verification_credits, if: :verified_at_changed?
  before_update -> { generate_token(:auth_token) }, if: :verified_at_changed?

  has_many :questions, dependent: :restrict_with_error
  has_many :answers, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :credits, dependent: :destroy
  has_many :orders, dependent: :destroy

  has_many :followed_users, foreign_key: :follower_id, class_name: "Follow"
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: "Follow"
  has_many :followers, through: :following_users

  has_secure_password
  acts_as_taggable_on :topics
  has_one_attached :profile_picture, dependent: :destroy do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :mini, resize_to_limit: [40, 40]
  end

  validates :name, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, if: :password_set?

  def verified?
    verified_at.present?
  end

  def email_activate
    update(email_confirm_token: nil, verified_at: Time.current)
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.now
    save
    UserMailer.forgot_password(id).deliver
  end

  def recompute_credits
    self.credits_count = self.credits.inject(0) { |sum, credit| sum += credit.amount }
    save!
  end

  def add_verification_credits
    credits.build({ amount: 5, creditable: User.find(1), description: 0 })
  end

  def generate_credits(amount, entity, description)
    credits.build({ amount: amount, creditable: entity, description: description })
    save
  end

  private

  def password_set?
    return !(self.password.blank? && !self.new_record?)
  end

  def send_confirmation_email
    UserMailer.registration_confirmation(id).deliver_later
  end

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  def feed
    @questions = Question.tagged_with(current_user.topic_list, :any => true).includes(:user, :rich_text_content, { answers: [:user, :rich_text_content] }, { comments: [:user] }, :topics).order(created_at: :desc).where.not(published_at: false)
    render json: @questions, each_serializer: QuestionSerializer, include: ["user", "answers.user", "answers.comments.user", "comments.user"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user, only: [:show]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :set_user_by_email_confirm_token, only: [:confirm_email]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t("confirm_email")
      redirect_to root_url
    else
      flash[:error] = t("error")
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: t("profile_update_success")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def confirm_email
    if @user.email_activate
      flash[:success] = t("email_activated")
      redirect_to login_url
    else
      flash[:error] = t("error")
      redirect_to root_url
    end
  end

  def follow
    @user = User.find(params[:id])
    current_user.followees << @user
    redirect_back(fallback_location: user_path(@user))
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.followed_users.find_by(followee_id: @user.id).destroy
    redirect_back(fallback_location: user_path(@user))
  end

  def credits
    @user = current_user
    @credits = current_user.credits
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_picture, topic_list: [])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_user_by_email_confirm_token
    @user = User.find_by_email_confirm_token(params[:id])
    unless @user
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_profile_picture_link(user)
    user.profile_picture.present? ? rails_blob_path(user.profile_picture.variant(:thumb), disposition: "attachment") : "default.jpeg"
  end

  def user_mini_picture_link(user)
    user.profile_picture.present? ? rails_blob_path(user.profile_picture.variant(:mini), disposition: "attachment") : "default.jpeg"
  end

  def change_password
    current_user.generate_change_password_token
    redirect_to edit_password_url(current_user.password_reset_token)
  end

  def row_class_helper(credit)
    if credit.amount > 0
      row_class = "table-success"
      row_type = "credit"
    else
      row_class = "table-danger"
      row_type = "debit"
    end
    [row_class, row_type]
  end
end

app/views/users/_form.html.erb
<%= render partial: 'shared/error_messages', locals: { model: @user }%>
<div class="row">
  <div class="col-md-4 offset-4">
    <%= form_with(model: @user, local: true) do |f| %>
      <div class="img-field">
        <%= image_tag user_profile_picture_link(@user), class: 'profile-img' %>
        <%= f.label :profile_picture, 'Upload New Profile Picture' %>
        <%= f.file_field :profile_picture, accept: 'image/png,image/gif,image/jpg' %>
      </div>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'mb-1 form-control' %>
      <% if @user.new_record? %>
        <div class="field">
          <%= f.label :email, 'Email: ' %>
          <%= f.text_field :email %>
        </div>
      <% else %>
        <div class="field">
          <span><b>Email: </b></span>
          <span><%= @user.email %></span>
        </div>
      <% end %>

      <%= render partial: 'topics/form',locals: { form: f, entity: current_user }%>
      <%= f.submit "Edit my account", class: "mt-2 btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_show-mini.html.erb
<div class="d-flex justify-content-between">
  <div class="d-flex">
    <%= image_tag user_mini_picture_link(user), class: 'profile-img rounded mini-img' %>
    <div class="ml-2">
      <Strong ><%= user.name %></Strong>
      <div class="desc"><%= extra_data %></div>
    </div>
  </div>
  <% if current_user %>
    <% if current_user.followees.include?(user) %>
      <%= button_to "Unfollow", unfollow_user_path(user), method: "POST",class:"btn btn-light" %>
    <% elsif user.id != current_user.id %>
      <%= button_to "Follow", follow_user_path(user), method: "POST",class:"btn btn-light "  %>
    <% end%>
  <% end %>
</div>

app/views/users/_user.html.erb
<h1>Hello, <%= @user.name %></h1>
<div class="col-md-4 offset-4">
  <div class="text-center">
    <%= image_tag user_profile_picture_link(@user), class: 'profile-img rounded mx-auto d-block' %>
    <div ><Strong><%= @user.name %></Strong></div>
    <div><%= @user.email %></div>
    <br />
    <div>Your auth token: <%= @user.auth_token %></div>
    <div>Your Credits: <%= @user.credits_count %></div>
    <%= link_to 'Your credits history', user_credits_path(@user) %>
    <%= link_to 'Buy_credits', credit_packs_path %>
    <div class= "d-flex justify-content-around">
      <%= button_to "Followers #{@user.followers.size}", user_followers_path(@user), method: :get, class: "mt-2 btn btn-primary" %>
      <%= button_to "Following #{@user.followees.size}", user_following_path(@user), method: :get, class: "mt-2 btn btn-primary" %>
    </div>
    <div>Your Topic of interests</div>
    <div class="topics-container">
      <%= render partial: 'topics/topic', collection: @user.topics %>
    </div>
    <%= button_to 'Edit Profile', edit_user_path, method: :get, class: "mt-2 btn btn-primary" %>
  </div>
</div>
<div class= "d-flex w-auto  mt-5">
  <div class="list-group border border-secondary w-50 mr-5">
    <div class= "border-bottom border-secondary text-center p-2">Your Published Questions</div>
    <%= render partial: 'questions/question', collection: @user.questions.where.not(published_at: nil) %>
  </div>
  <div class="list-group border border-secondary w-50 ml-5">
    <div class= "border-bottom border-secondary text-center p-2">Your Drafted/Unpublished Questions</div>
    <%= render partial: 'questions/question', collection: @user.questions.where(published_at: nil) %>
  </div>
</div>

app/views/users/credits.html.erb
<h1 class= "container">Hello, <%= @user.name %></h1>
<div class = " container">
  <Strong> Your Transactions</Strong>
  <table class="table">
    <thead>
      <tr>
        <% number = 0 %>
        <th scope="col">#</th>
        <th scope="col">Description</th>
        <th scope="col">Time</th>
        <th scope="col">Amount</th>
        <th scope="col">Type</th>
      </tr>
    </thead>
    <tbody>
      <% @credits.each do |credit| %>
        <% row_class, row_type = row_class_helper(credit)%>
        <tr class = "<%= row_class %>">
          <th scope="row"><%= number = number.next %></th>
          <td><%= credit.description %></td>
          <td><%= credit.created_at.strftime('%m/%d %I:%M %p') %></td>
          <td><%= credit.amount %></td>
          <td><%= row_type %></td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/users/edit.html.erb
<%= render partial: 'form' %>

app/views/users/followees.html.erb
<div class="col-md-4 offset-4">
  <% current_user.followees.each do |followee| %>
    <%= render partial: 'users/show-mini',locals: {user: followee, extra_data: nil}  %>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="col-md-4 offset-4">
<% current_user.followers.each do |follower| %>
<%= render partial: 'users/show-mini',locals: {user: follower, extra_data: nil}  %>
<% end %>
</div>

app/views/users/new.html.erb
<h1 class='text-center'>Sign up</h1>
<div class="row">
  <div class="col-md-4 offset-4">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render partial: 'shared/error_messages', locals: { model: @user }%>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'mb-1 form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'mb-1 form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'mb-1 form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'mb-1 form-control' %>
      <%= f.submit "Create my account", class: "mt-2 btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render partial: 'user' %>