config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "/signup", to: "users#new"
  resources :users do
    get "/followers", to: "users#followers"
    get "/following", to: "users#followees"
    get "credits"
    member do
      get :confirm_email
      post "follow"
      post "unfollow"
    end
  end

  resources :credit_packs, only: [:index]
  resource :transactions, only: [:create]
  resources :orders, only: [:create], param: :code do
    get "checkout", on: :member
    get "success", on: :member
    get "failure", on: :member
  end
  resources :passwords
  resources :sessions, only: [:new, :create, :destroy]
  resources :reports
  resources :questions, param: :permalink do
    resources :answers do
      resources :comments
    end
    resources :comments
    collection do
      match "search" => "questions#search", via: [:get, :post], as: :search
    end
  end

  namespace :api do
    get 'feed', to: 'users#feed', format: true, constraints: { format: :json }
    resources :topics, only: [:index, :show], param: :topic do
      get "/:x", to: "topics#show", on: :member
    end
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
end

app/models/answer.rb
class Answer < ApplicationRecord
  include CommentsHandler
  include ReportsHandler
  include VotesHandler

  scope :published_answers, -> { where.not(published_at: :nil) }

  after_create_commit :send_confirmation_email
  validates_presence_of :content

  belongs_to :user
  belongs_to :question
  is_creditable
  has_rich_text :content

  def send_confirmation_email
    QuestionMailer.answer_posted(self.id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question
  before_action :set_answer, only: [:edit, :destroy]

  def new
    @answer = @question.answers.build
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params.merge(user: current_user, published_at: Time.now))
    if @answer.save
      redirect_to @question, notice: t("answer_publish_success")
    else
      flash[:error] = t("answer_publish_error")
      render "questions/show", status: :unprocessable_entity
    end
  end

  def destroy
    if @answer.user == current_user
      if @answer.destroy
        redirect_to @question, notice: t("answer_delete_success")
      else
        flash[:error] = t("answer_delete_error")
        render "questions/show", status: :unprocessable_entity
      end
    else
      flash[:error] = t("answer_user_error")
      render "questions/show", status: :unprocessable_entity
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:user_id, :content, :question_permalink)
  end

  def set_question
    @question = Question.find_by(permalink: params[:question_permalink])
  end

  def set_answer
    @answer = Answer.find_by(params[:id])
  end
end

app/views/answers/_answer.html.erb
<div class="question mt-2">
  <%= render partial: 'users/show-mini', locals: {user: User.find(answer.user_id), extra_data: "Answered: #{answer.created_at.strftime('%m/%d %I:%M %p')}"} %>
  <div class="desc"><%= answer.content.to_plain_text %></div>
  <% if answer.user_id == current_user&.id  %>
    <%= button_to "Delete Answer", question_answer_path(entity.permalink , answer.id ),method: :delete, class: "mt-2 btn btn-secondary", form: { data: {turbo_confirm: 'Are you sure?'}}  %>
  <%end  %>
   <% if logged_in? %>
  <%= link_to 'Report this Answer', new_report_path(reportable_id: answer.id, reportable_type: answer.class) %>
  <%= render partial: 'votes/vote_form', locals: {resource: answer} %>
  <%= render partial: 'comments/form',locals:{ entity: answer, comment: answer.comments.build, parent_entity: entity } %>
  <% end %>
  <div class= "answer-comm">
    <%= render partial: 'comments/comment', collection: answer.comments.where.not(id: nil),locals:{ entity: answer, parent_entity: entity } %>
  </div>
</div>

app/views/answers/_form.html.erb
<div>
  <%= form_with(model: [entity,answer]) do |f| %>
    <% if @answer %>
      <%= render partial: 'shared/error_messages', locals: { model: @answer}%>
    <% end %>
    <%= f.label :content, 'Write an Answer' %>
    <%= f.rich_text_area :content, class: 'mb-1 form-control' %>
    <%= f.submit "Submit Answer", class: "mt-2 btn btn-primary" %>
  <% end %>
</div>