config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "/signup", to: "users#new"
  resources :users do
    get "/followers", to: "users#followers"
    get "/following", to: "users#followees"
    get "credits"
    member do
      get :confirm_email
      post "follow"
      post "unfollow"
    end
  end

  resources :credit_packs, only: [:index]
  resource :transactions, only: [:create]
  resources :orders, only: [:create], param: :code do
    get "checkout", on: :member
    get "success", on: :member
    get "failure", on: :member
  end
  resources :passwords
  resources :sessions, only: [:new, :create, :destroy]
  resources :reports
  resources :questions, param: :permalink do
    resources :answers do
      resources :comments
    end
    resources :comments
    collection do
      match "search" => "questions#search", via: [:get, :post], as: :search
    end
  end

  namespace :api do
    get 'feed', to: 'users#feed', format: true, constraints: { format: :json }
    resources :topics, only: [:index, :show], param: :topic do
      get "/:x", to: "topics#show", on: :member
    end
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
end

app/views/admin/admins/_disable_entity_form.html.erb
<%= form_with url: disable_entity_admin_path, method: :patch do |form| %>
  <%= form.hidden_field :entity_id, value: entity.id %>
  <%= form.hidden_field :entity_type, value: entity.class %>
  <% if entity.published? %>
      <%= form.submit "Unpublish #{entity.class.name}", class: "mt-2 btn btn-primary"  %>
  <% end %>
<% end %>

app/views/admin/admins/answers.html.erb
<div class = " container">  <Strong>Answer list</Strong>
  <table class="table">
    <thead>
      <tr>
        <% number = 0 %>
        <th scope="col">#</th>
        <th scope="col">Answer</th>
        <th scope="col">Question</th>
        <th scope="col">View</th>
        <th scope="col">Unpublish</th>
      </tr>
    </thead>
    <% @answers.each do |answer| %>
      <tr>
        <th scope="row"><%= number = number.next %></th>
        <td><%= answer.content.to_plain_text.truncate(100) %></td>
        <td><%= answer.question.title %></td>
        <td><%= link_to 'View Question', question_path(answer.question.permalink) %></td>
        <td><%= render partial: 'disable_entity_form', locals: { entity: answer } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/admins/comments.html.erb
<div class = " container">  <Strong>Comment list</Strong>
  <table class="table">
    <thead>
      <tr>
        <% number = 0 %>
        <th scope="col">#</th>
        <th scope="col">Comment</th>
        <th scope="col">Comment On</th>
        <th scope="col">Title</th>
        <th scope="col">View</th>
        <th scope="col">Unpublish</th>
      </tr>
    </thead>
    <% @comments.each do |comment| %>
      <tr>
        <th scope="row"><%= number = number.next %></th>
        <td><%= comment.content %></td>
        <td><%= comment.commentable_type %></td>
        <% if comment.commentable_type == 'Answer' %>
          <td><%= comment.commentable.question.title.truncate(40) %><br/>
            <%= comment.commentable.content.to_plain_text.truncate(40) %></td>
          <td><%= link_to 'View Comment', question_path(comment.commentable.question.permalink) %></td>
        <% else %>
          <td><%= comment.commentable.title %></td>
          <td><%= link_to 'View Comment', question_path(comment.commentable.permalink) %></td>
        <% end %>
        <td><%= render partial: 'disable_entity_form', locals: { entity: comment } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/admins/questions.html.erb
<div class = " container">  <Strong>Question list</Strong>
  <table class="table">
    <thead>
      <tr>
        <% number = 0 %>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Content</th>
        <th scope="col">File Link</th>
        <th scope="col">Topics</th>
        <th scope="col">View</th>
        <th scope="col">Unpublish</th>
      </tr>
    </thead>
    <% @questions.each do |question| %>
      <tr>
        <th scope="row"><%= number = number.next %></th>
        <td><%= question.title %></td>
        <td><%= question.content.to_plain_text.truncate(100) %></td>
        <td>
          <% if question.pdf_attachment.present?%>
            <%= link_to  "Open PDF",rails_blob_path(question.pdf_attachment), class: "d-block" %>
          <% else%>
            No File
          <% end%></td>
        <td><%= render partial: 'topics/topic', collection: question.topics %></td>
        <td><%= link_to 'View Question', question_path(question.permalink) %></td>
        <td><%= render partial: 'disable_entity_form', locals: { entity: question } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/admins/show.html.erb
<div class= 'container'>
  <h1>Hello Admin</h1>
  <ul class="list-group">
    <li class="list-group-item"><%= link_to 'Browse Users', users_admin_path %></li>
    <li class="list-group-item"><%= link_to 'Browse Questions', questions_admin_path %></li>
    <li class="list-group-item"><%= link_to 'Browse Answers', answers_admin_path %></li>
    <li class="list-group-item"><%= link_to 'Browse Comments', comments_admin_path %></tr>
  </tbody>
</table>
</div>
</div>

app/views/admin/admins/users.html.erb
<div class = " container">  <Strong>User list</Strong>
  <table class="table">
    <thead>
      <tr>
        <% number = 0 %>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Role</th>
        <th scope="col">View</th>
        <th scope="col">Disable/enable</th>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= number = number.next %></th>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'View User', user_path(user) %></td>
        <td><%= form_with url: disable_user_admin_path, method: :patch do |form| %>
            <%= form.hidden_field :user_id, value: user.id %>
            <% if user.disabled_at? %>
              <%= form.submit "Enable User", class: "mt-2 btn btn-primary" %>
            <% else %>
              <%= form.submit "Disable User",name: 'disabled' class: "mt-2 btn btn-primary" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>