config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "/signup", to: "users#new"
  resources :users do
    get "/followers", to: "users#followers"
    get "/following", to: "users#followees"
    get "credits"
    member do
      get :confirm_email
      post "follow"
      post "unfollow"
    end
  end

  resources :credit_packs, only: [:index]
  resource :transactions, only: [:create]
  resources :orders, only: [:create], param: :code do
    get "checkout", on: :member
    get "success", on: :member
    get "failure", on: :member
  end
  resources :passwords
  resources :sessions, only: [:new, :create, :destroy]
  resources :reports
  resources :questions, param: :permalink do
    resources :answers do
      resources :comments
    end
    resources :comments
    collection do
      match "search" => "questions#search", via: [:get, :post], as: :search
    end
  end

  namespace :api do
    get 'feed', to: 'users#feed', format: true, constraints: { format: :json }
    resources :topics, only: [:index, :show], param: :topic do
      get "/:x", to: "topics#show", on: :member
    end
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
end

app/models/credit_pack.rb
class CreditPack < ApplicationRecord
    validates :price, :credits, presence:true , numericality: true
end

app/controllers/credit_packs_controller.rb
class CreditPacksController < ApplicationController
    def index
        @packs = CreditPack.all
    end
end

app/views/credit_packs/_pack.html.erb
<div class="col-md-4">
  <div class="card p-3">
    <div class="d-flex flex-row mb-3">
      <%= image_tag 'dollar.png', width: 70 %>
      <div class="d-flex flex-column ml-2"><span> Credit Pack</span><span class="text-black-50">QuoraClone Credits</span></div>
    </div>
    <h6><%= pack.credits %> Credits for <%= pack.price %> </h6>
    <div class="d-flex justify-content-between install mt-3"><span>Buy Now</span><span class="text-primary"><%= form_with url: orders_path(pack_id: pack.id) do |form| %>
          <%= form.submit 'Buy credits', class: 'btn btn-primary' %>
        <% end %></span></div>
  </div>
</div>

app/views/credit_packs/index.html.erb
<div class="container mt-5">
  <div class="row">
    
        <%= render partial: 'pack', collection: @packs %>

  </div>
</div>

      